name: upload-chart
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Helm push chart
      env:
        HELM_REPO_ACCESS_TOKEN: ${{ secrets.HELM_REPO_ACCESS_TOKEN }}
      run: |
        sudo snap install helm --classic
        helm plugin install https://github.com/chartmuseum/helm-push
        helm push chart/elastabot https://charts.banzaicloud.io/gh/Codesim-LLC
