name: upload-chart
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        mkdir -p /tmp/out
        sudo snap install helm --classic
        helm package chart/elastabot -d /tmp/out
        helm plugin install https://github.com/chartmuseum/helm-push
        helm repo add codesim cm://helm.codesim.com
        helm push -f /tmp/out/* codesim
